config/routes.rb
Rails.application.routes.draw do

  root 'games#index'
  resources :users, only: [:create, :new, :show, :edit, :update]
  resources :games, only: [:index, :show, :edit, :update]
  resources :boxes, only: [:update]
  resources :scores
  namespace :admin do
    resources :games, except: [:index, :show, :edit, :update]
  end

  resources :sessions, only: [:create]
  get 'signin'   => 'sessions#new'
  get 'signout'  => 'sessions#destroy'

end

app/models/score.rb
class Score < ActiveRecord::Base
  # TODO: add tests for status presence
  enum quarter: { first_quarter: 1, second_quarter: 2, third_quarter: 3, fourth_quarter: 4 }
  enum status: { CURRENT: 0, AGED: 1 }

  # change quarter to be an enum and reference box in next migration

  validates_presence_of :home_score
  validates_presence_of :away_score
  validates_presence_of :quarter
  validates_presence_of :game_info
  validates_presence_of :status

  # should not let a new score be less than an old score.  Raise an issue if this happens

  after_initialize :default_values
  after_save :game_updater # TODO: should actually call score updator which calls game updator... but I want the tests to pass for now

  scope :finals, -> { where(is_final: true) }
  scope :current, -> { where(status: 0) }
  scope :aged, -> { where(status: 1) }

  private

  def default_values
    self.is_final ||= false
  end

  def game_updater
    ScoreUpdater.update!(self)
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :require_login
  before_action :is_editable, only: [:edit]

  def create
    @score = Score.new(score_params)
    if @score.save
      flash[:error] = 'Score saved!'
      redirect_to games_path
    else
      flash[:error] = @score.errors.full_messages.first
      render :back
    end
  end

  def edit
  end

  def new
    @score = Score.new
    @quarter_options = { first_quarter: 1, second_quarter: 2, third_quarter: 3, fourth_quarter: 4 }.to_a.freeze
  end

  def index
    @scores = Score.all
    @games = Game.by_description(@scores.pluck(:game_info))
  end

  def show
    @score = Score.find(params[:id])
  end

  def update
    @score = Score.find(params[:id])
    @score.update(score_params)

    if @score.save
      flash[:success] = 'Score saved!'
      redirect_to root_path
    else
      flash[:error] = 'Score not saved'
      redirect_to :back
    end
  end

  private

  def score_params
    params.require(:score).permit(:game_info, :away_score, :home_score, :quarter, :is_final)
  end
end

app/views/scores/index.html.erb
<% @games.each do |game| %>
  <div><h3><%= "#{game.description}" %></h3></div>
  <% @scores.each do |score| %>
    <% if score.game_info == game.description %>
      <div><%= "#{game.away_team} #{score.away_score} | #{game.home_team} #{score.home_score} in the #{score.quarter.titleize}" %></div>
    <% end %>
  <% end %>
  <hr>
<% end %>

<%= link_to "Add New Score", new_score_path %>

app/views/scores/index.mobile.erb
<% @games.each do |game| %>
  <div><h3><%= "#{game.description}" %></h3></div>
  <% @scores.each do |score| %>
    <% if score.game_info == game.description %>
      <div><%= "#{game.away_team} #{score.away_score} | #{game.home_team} #{score.home_score} in the #{score.quarter.titleize}" %></div>
    <% end %>
  <% end %>
  <hr>
<% end %>

<%= link_to "Add New Score", new_score_path %>

app/views/scores/new.html.erb
<%= form_for @score do |f|%>
<div id="new-score-form">
  <%= f.label :game_info %>
  <%= f.collection_select :game_info, Game.order(:description), :description, :description %>
  <%= f.label :away_score %>
  <%= f.number_field(:away_score, in: 0..70) %>
  <%= f.label :home_score %>
  <%= f.number_field(:home_score, in: 0..70) %>
  <%= f.label :quarter %>
  <%= f.select(:quarter) do %>
    <% @quarter_options.each do |c| -%>
      <%= content_tag(:option, c.last, value: c.first) %>
    <% end %>
  <% end %>
  <%= f.label(:is_final, "Is this a final score?") %>
  <%= f.check_box(:is_final) %>

  <div class="submit">
    <input type="submit" value="SUBMIT" class="button-red" id="signin-button"/>
    <div class="ease"></div>
  </div>
</div>
<% end %>

app/views/scores/new.mobile.erb
<%= form_for @score do |f|%>
<div id="new-score-form">
<div class="new-score-form">
  <%= f.label :game_info %>
  <%= f.collection_select :game_info, Game.order(:description), :description, :description %>
</div>
<div class="new-score-form">
  <%= f.label :away_score %>
  <input min="0" max="70" type="number" name="score[away_score]" id="score_away_score" pattern="\d*">
</div>
<div class="new-score-form">
  <%= f.label :home_score %>
  <input min="0" max="70" type="number" name="score[home_score]" id="score_home_score" pattern="\d*">
</div>
<div class="new-score-form">
  <%= f.label :quarter %>
  <%= f.select(:quarter) do %>
    <% @quarter_options.each do |c| -%>
      <%= content_tag(:option, c.last, value: c.first) %>
    <% end %>
  <% end %>
</div>
<div class="new-score-form">
  <%= f.label(:is_final, "Is this a final score?") %>
  <%= f.check_box(:is_final) %>
</div>


  <div class="submit">
    <input type="submit" value="SUBMIT" class="button-red" id="signin-button"/>
    <div class="ease"></div>
  </div>
</div>
<% end %>