config/routes.rb
Rails.application.routes.draw do

  root 'games#index'
  resources :users, only: [:create, :new, :show, :edit, :update]
  resources :games, only: [:index, :show, :edit, :update]
  resources :boxes, only: [:update]
  resources :scores
  namespace :admin do
    resources :games, except: [:index, :show, :edit, :update]
  end

  resources :sessions, only: [:create]
  get 'signin'   => 'sessions#new'
  get 'signout'  => 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :boxes
  has_secure_password

  EMAIL_REGEX = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i

  validates :name, :email, :password, presence: true
  validates :name, :email, uniqueness: true
  validates :email, format: EMAIL_REGEX

  # TODO: strangely cannot call user.boxes
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show, :edit, :update]

  def edit
    @user = User.find(@current_user.id)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:error] = @user.errors.full_messages.first
      render :new
    end
  end

  def new
    @user = User.new
    render layout: false if request.xhr?
  end

  def show
    @boxes = Box.by_user(@current_user)
    @winning_boxes = Box.where(is_winner: true)
    user_games = Game.by_id(@boxes.pluck(:game_id).uniq)
    @entered_user_games = user_games.created
    @active_user_games = user_games.active
    @complete_user_games = user_games.active
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(edit_user_params)
      flash[:error] = 'Saved your info'
      redirect_to user_path(@current_user)
    else
      flash[:error] = @user.errors.full_messages.first
      redirect_to :back
    end
  end

  private

  def edit_user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def user_params
    params.permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.erb
<%= form_for(@user) do |f| %>
<div id="new-user-form">
  <p id="user-name">
    <%= f.text_field :name, class: 'feedback-input' %>
  </p>
  <p id="email">
    <%= f.email_field :email, class: 'feedback-input' %>
  </p>
  <p id="password">
    <%= f.password_field :password, placeholder: "Password", class: 'feedback-input' %>
  </p>
  <p id="password-confirmation">
    <%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: 'feedback-input' %>
  </p>
  <div class="submit">
    <%= f.submit "UPDATE", class: "button-red" %>
    <div class="ease"></div>
  </div>
</div>
<% end %>

app/views/users/_form.erb
<%= form_tag users_path, method: 'POST' do %>
<div id="new-user-form">
  <p id="user-name">
    <input name="name" type="text" class="feedback-input" placeholder="Username" />
  </p>
  <p id="password">
    <input name="email" type="text" class="feedback-input" placeholder="Email" />
  </p>
  <p id="name">
    <input name="password" type="password" class="feedback-input" placeholder="Password" />
  </p>
  <p id="password">
    <input name="password_confirmation" type="password" class="feedback-input" placeholder="Confirm Password" />
  </p>
  <div class="submit">
    <input type="submit" value="CREATE USER" class="button-red" id="create-user"/>
    <div class="ease"></div>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<%= render 'edit_form' %>

app/views/users/edit.mobile.erb
<%= render 'edit_form' %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/new.mobile.erb
<%= form_tag users_path, method: 'POST' do %>
<div id="new-user-form">
  <p id="user-name">
    <input name="name" type="text" class="feedback-input" placeholder="Username" />
  </p>
  <p id="password">
    <input name="email" type="text" class="feedback-input" placeholder="Email" />
  </p>
  <p id="name">
    <input name="password" type="password" class="feedback-input" placeholder="Password" />
  </p>
  <p id="password">
    <input name="password_confirmation" type="password" class="feedback-input" placeholder="Confirm Password" />
  </p>
  <div class="submit">
    <input type="submit" value="CREATE USER" class="button-red" id="create-user"/>
    <div class="ease"></div>
  </div>
</div>
<% end %>

app/views/users/show.html.erb
<h2>Open Games</h2>
<div class="col-sm-12">
  <% @not_active_user_games.each do |game| %>
    <%= link_to("#{game.away_team} at #{game.home_team}", edit_game_path(game)) %></br>
    <% @boxes.by_game(game).each do |box| %>
      <div class="row">
        <%= render partial: "boxes/box", :locals => { :box => box, :winning_boxes => @winning_boxes } %>
        <%= "#{game.away_team}: #{box.away_team_num} and #{game.home_team}: #{box.home_team_num}" %>
      </div>
    <% end %>
  <% end %>
  <h2>Locked Games</h2>
  <% @active_user_games.each do |game| %>
    <%= link_to("#{game.away_team} at #{game.home_team}", game_path(game)) %></br>
    <% @boxes.by_game(game).each do |box| %>
      <div class="row">
        <%= render partial: "boxes/box", :locals => { :box => box, :winning_boxes => @winning_boxes } %>
        <%= "#{game.away_team}: #{box.away_team_num} and #{game.home_team}: #{box.home_team_num}" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/show.mobile.erb
<h2>Entered Games</h2>
  <% @entered_user_games.each do |game| %>
    <%= link_to("#{game.away_team} at #{game.home_team}", edit_game_path(game)) %></br>
      <% if @boxes.size > 1 %>
        <%= "#{@boxes.size} boxes picked" %>
      <% else %>
        <%= "1 box picked" %>
      <% end %>
  <% end %>
  <h2>Active Games</h2>
  <% @active_user_games.each do |game| %>
    <%= link_to("#{game.away_team} at #{game.home_team}", game_path(game)) %></br>
    <% @boxes.by_game(game).each do |box| %>
      <div class="row">
        <%= render partial: "boxes/box", :locals => { :box => box, :winning_boxes => @winning_boxes } %>
        <%= "#{game.away_team}: #{box.away_team_num} and #{game.home_team}: #{box.home_team_num}" %>
      </div>
    <% end %>
  <% end %>
  <h2>Completed Games</h2>
  <% @complete_user_games.each do |game| %>
    <%= link_to("#{game.away_team} at #{game.home_team}", game_path(game)) %></br>
    <% @boxes.by_game(game).each do |box| %>
      <div class="row">
        <%= render partial: "boxes/box", :locals => { :box => box, :winning_boxes => @winning_boxes } %>
        <%= "#{game.away_team}: #{box.away_team_num} and #{game.home_team}: #{box.home_team_num}" %>
      </div>
    <% end %>
  <% end %>
</div>
<%= link_to("Edit User Info", edit_user_path(@current_user)) %>