config/routes.rb
Rails.application.routes.draw do

  root 'games#index'
  resources :users, only: [:create, :new, :show, :edit, :update]
  resources :games, only: [:index, :show, :edit, :update]
  resources :boxes, only: [:update]
  resources :scores
  namespace :admin do
    resources :games, except: [:index, :show, :edit, :update]
  end

  resources :sessions, only: [:create]
  get 'signin'   => 'sessions#new'
  get 'signout'  => 'sessions#destroy'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :boxes, -> { order 'home_team_coord ASC, away_team_coord ASC' }, dependent: :destroy

  COORDINATES = %w( A B C D E F G H I J ).freeze
  BOX_NUMBERS = Array(0..9).freeze

  enum status: { CREATED: 0, ACTIVE: 1, COMPLETED: 2 }

  accepts_nested_attributes_for :boxes

  # TODO: seems I can't call boxes on games either
  # TODO add test for setting box numbers

  validate :away_team_present
  validate :home_team_present

  after_initialize :constructor
  before_save :populate_numbers

  scope :created, -> { where(status: 0) }
  scope :active, -> { where(status: 1) }
  scope :completed, -> { where(status: 2) }
  scope :by_away_team, ->(away_team) { where(away_team: away_team) }
  scope :by_description, ->(description) { where(description: description) }
  scope :by_home_team, ->(home_team) { where(home_team: home_team) }
  scope :by_id, ->(id) { where(id: id) }

  private

  def away_team_present
    errors.add(:away_team, "can't be blank") if away_team.blank?
  end

  def constructor
    return unless new_record?
    self.description = "#{away_team} vs #{home_team}"
    game_boxes = COORDINATES.product(COORDINATES)
    game_boxes.map { |box| boxes.build(home_team_coord: box[0], away_team_coord: box[1]) }
    # self.save!
  end

  def coords_nums_hash
    Hash[COORDINATES.zip(BOX_NUMBERS.shuffle)]
  end

  def home_team_present
    errors.add(:home_team, "can't be blank") if home_team.blank?
  end

  def populate_numbers
    return if status == 'CREATED' || boxes.pluck(:home_team_num).uniq != [nil] || boxes.pluck(:away_team_num).uniq != [nil]
    random_home_numbers_hash = coords_nums_hash
    random_away_numbers_hash = coords_nums_hash
    boxes.each do |box|
      box.home_team_num = random_home_numbers_hash[box.home_team_coord]
      box.away_team_num = random_away_numbers_hash[box.away_team_coord]
    end
  end
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < ApplicationController
  before_action :require_admin
  before_filter :check_for_new_cancel, only: [:create]
  before_filter :check_for_edit_cancel, only: [:update]

  def create
    @game = Game.new(game_params)

    if @game.save
      flash[:success] = 'Game saved!'
      redirect_to root_path
    else
      flash[:error] = 'Game not saved'
      redirect_to :back
    end
  end

  def destroy
    if Game.find(params[:id]).destroy
      flash[:success] = 'Game deleted'
      redirect_to root_path
    else
      flash[:error] = 'Game not deleted'
      redirect_to :back
    end
  end

  def new
    @game = Game.new
  end

  private

  # TODO: GET RID OF THIS METHOD
  def check_for_new_cancel
    redirect_to root_path if params[:cancel] == 'Cancel'
  end

  # TODO: GET RID OF THIS METHOD
  def check_for_edit_cancel
    redirect_to game_path if params[:cancel] == 'Cancel'
  end

  def game_params
    params.require(:game).permit(:away_team, :home_team)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :require_login
  before_action :is_editable, only: [:edit]
  before_filter :check_for_new_cancel, only: [:create]

  def edit
  end

  def new
    @game = Game.new
  end

  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
    # TODO: change winning boxes logic to be found by the game_updater and presented through the game presenter
  end

  def update
    @game = Game.find(params[:id])
    @game.update(game_params)

    if @game.save
      flash[:success] = 'Game saved!'
      redirect_to root_path
    else
      flash[:error] = 'Game not saved'
      redirect_to :back
    end
  end

  private

  def game_params
    params.require(:game).permit(:away_team, :home_team, boxes_attributes: [:id, :is_taken])
  end

  def is_editable
    @game = Game.find(params[:id])
    if @game.status == 'ACTIVE'
      flash[:error] = 'Sorry, bruh... Game is live.'
      redirect_to :back
    else
      return @game
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def logged_in?
  end
end

app/views/games/_winners.html.erb
<% unless first_winning_name.nil? %>
<p>
  <% if second_winning_name.nil? %>
    <%= "Winning: " %>
  <% else %>
    <%= "Winner: " %>
  <% end %>
<%= "Name: #{first_winning_name}" unless first_winning_name.nil? %>
<%= "#{@game.home_team}: #{@game.first_quarter_home_score} #{@game.away_team}: #{@game.first_quarter_away_score}" %>
</p>
<% end %>
<% unless second_winning_name.nil? %>
<p>
  <% if third_winning_name.nil? %>
    <%= "Winning: " %>
  <% else %>
    <%= "Winner: " %>
  <% end %>
<%= "Name: #{second_winning_name}" unless second_winning_name.nil? %>
<%= "#{@game.home_team}: #{@game.second_quarter_home_score} #{@game.away_team}: #{@game.second_quarter_away_score}" %>
</p>
<% end %>
<% unless third_winning_name.nil? %>
<p>
  <% if fourth_winning_name.nil? %>
    <%= "Winning: " %>
  <% else %>
    <%= "Winner: " %>
  <% end %>
<%= "Name: #{third_winning_name}" unless third_winning_name.nil? %>
<%= "#{@game.home_team}: #{@game.third_quarter_home_score} #{@game.away_team}: #{@game.third_quarter_away_score}" %>
</p>
<% end %>
<% unless fourth_winning_name.nil? %>
<p>
  <%= "Winning: "%>
<%= "Name: #{fourth_winning_name}" unless fourth_winning_name.nil? %>
<%= "#{@game.home_team}: #{@game.fourth_quarter_home_score} #{@game.away_team}: #{@game.fourth_quarter_away_score}" %>
</p>
<% end %>

app/views/games/edit.erb
<% present @game do |game_presenter| %>
<div class="box effect2" id="show-game">
  <div id="box-container">
    <div id='main_wrapper' class='dtable'>
      <div id='control_panel_wrapper' class='drow'>
        <div id='away-team-space' class='dcell'><h1 class="text-center"></h1></div>
        <div id='away-team' class='dcell'><h1 class="text-center"><%= @game.away_team %></h1></div>
      </div>
    </div>
    <div class='dtable'>
      <div id='bottom_wrapper' class='drow'>
        <div id='home-team' class='dcell'><h1 class="rotate home-team"><%= @game.home_team %></h1></div>
        <div id='chart_container' class='dcell'>
          <div class='dtable'>
            <div id='bottom_wrapper' class='drow'>
              <% game_presenter.away_letters.each do |away_number| %>
              <div class='box-cell dcell grid-letters'><h3><%= away_number %></h3></div>
              <% end %>
            </div>
          </div>
          <%- @game.boxes.each do |box| %>
          <%= render partial: "boxes/box_form", :locals => { :box => box } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/games/index.erb
<h4>Open Games</h4>
<% @games.created.each do |game| %>
<%= link_to("#{game.name}", edit_game_path(game), class: "open-game") %></br>
<% end %>
<h4>Locked Games</h4>
<% @games.active.each do |game| %>
<%= link_to("#{game.name}", game_path(game), class: "locked-game") %></br>
<hr>
<% end %>
<% if @user_boxes %>
<h2><%= link_to("Your Games", user_path(@current_user)) %></h2>
<% end %>
<% if @current_user.role == "admin" %>
<h2><%= link_to("Make a Game", new_admin_game_path) %></h2>
<% end %>

app/views/games/index.mobile.erb
<h4>Open Games</h4>
<% @games.created.each do |game| %>
<%= link_to("#{game.name}", edit_game_path(game), class: "open-game") %></br>
<% end %>
<h4>Locked Games</h4>
<% @games.active.each do |game| %>
<%= link_to("#{game.name}", game_path(game), class: "locked-game") %></br>
<hr>
<% end %>
<% if @user_boxes %>
<h2><%= link_to("Your Games", user_path(@current_user)) %></h2>
<% end %>
<% if @current_user.role == "admin" %>
<h2><%= link_to("Make a Game", new_admin_game_path) %></h2>
<% end %>

app/views/games/new.erb
<%= form_for(@game) do |f| %>
  Away Team: <%= f.text_field :away_team %>
  Home Team: <%= f.text_field :home_team %>
  <%= f.submit %>
  <%= f.submit "Cancel", :name => 'cancel' %>
<% end %>

app/views/games/show.erb
<% present @game do |game_presenter| %>
<%= render partial: "winners", :locals => { :first_winning_name => @game.first_quarter_winner,
                                            :second_winning_name => @game.second_quarter_winner,
                                            :third_winning_name => @game.third_quarter_winner,
                                            :fourth_winning_name => @game.fourth_quarter_winner  } %>
<div class="box effect2" id="show-game">
<div id="box-container">
  <div id='main_wrapper' class='dtable'>
    <div id='control_panel_wrapper' class='drow'>
      <div id='away-team-space' class='dcell'><h1 class="text-center"></h1></div>
      <div id='away-team' class='dcell'><h1 class="text-center"><%= @game.away_team %></h1></div>
    </div>
  </div>
  <div class='dtable'>
    <div id='bottom_wrapper' class='drow'>
      <div id='home-team' class='dcell'><h1 class="rotate home-team"><%= @game.home_team %></h1></div>
      <div id='chart_container' class='dcell'>
        <div class='dtable'>
          <div id='bottom_wrapper' class='drow'>
            <% game_presenter.away_numbers.each do |away_number| %>
            <div class='box-cell dcell grid-letters'><h3><%= away_number %></h3></div>
            <% end %>
          </div>
        </div>
        <%- @game.boxes.each do |box| %>
        <%= render partial: "boxes/box", :locals => { :box => box, :winning_boxes => @winning_boxes } %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>
<% end %>

app/views/games/show.mobile.erb
<% present @game do |game_presenter| %>
<%= @game.name %>
<%= render partial: "winners", :locals => { :first_winning_name => @game.first_quarter_winner,
                                            :second_winning_name => @game.second_quarter_winner,
                                            :third_winning_name => @game.third_quarter_winner,
                                            :fourth_winning_name => @game.fourth_quarter_winner  } %>
<div class="box effect2" id="show-game">
<div id="box-container">
  <div id='main_wrapper' class='dtable'>
    <div id='control_panel_wrapper' class='drow'>
      <div id='away-team-space' class='dcell'><h1 class="text-center"></h1></div>
      <div id='away-team' class='dcell'><h1 class="text-center"><%= @game.away_team %></h1></div>
    </div>
  </div>
  <div class='dtable'>
    <div id='bottom_wrapper' class='drow'>
      <div id='home-team' class='dcell'><h1 class="rotate home-team"><%= @game.home_team %></h1></div>
      <div id='chart_container' class='dcell'>
        <div class='dtable'>
          <div id='bottom_wrapper' class='drow'>
            <% game_presenter.away_numbers.each do |away_number| %>
            <div class='box-cell dcell grid-letters'><h3><%= away_number %></h3></div>
            <% end %>
          </div>
        </div>
        <%- @game.boxes.each do |box| %>
        <%= render partial: "boxes/box", :locals => { :box => box, :winning_boxes => @winning_boxes } %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>
<% end %>