config/routes.rb
Rails.application.routes.draw do

  root 'games#index'
  resources :users, only: [:create, :new, :show, :edit, :update]
  resources :games, only: [:index, :show, :edit, :update]
  resources :boxes, only: [:update]
  resources :scores
  namespace :admin do
    resources :games, except: [:index, :show, :edit, :update]
  end

  resources :sessions, only: [:create]
  get 'signin'   => 'sessions#new'
  get 'signout'  => 'sessions#destroy'

end

app/views/layouts/_flash.html.erb
<div id="flash_msg_container">
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key.to_sym) %> fade in">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/_flash.mobile.erb
<div id="flash_msg_container">
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key.to_sym) %> fade in">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true if !mobile_device? %>
  <%= stylesheet_link_tag 'mobile' if mobile_device? %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag '/images/favicon.ico', rel: 'apple-touch-icon', type: 'image/png' %>
  <meta name="viewport" content="initial-scale=1.0">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-transparent">
  <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
</head>
<% if @current_user %>
<html>
  <body>
    <header>
      <h1 id="banner"><%= link_to 'BOXED IN', root_path %></h1>
      <div class="button_container" id="toggle">
        <span class="top"></span>
        <span class="middle"></span>
        <span class="bottom"></span>
      </div>
    </header>
    <div class="overlay" id="overlay">
      <nav class="overlay-menu">
        <ul>
          <li><%= link_to 'Games', games_path %></li>
          <li><%= link_to 'Scores', scores_path %></li>
          <li><%= link_to 'My Account', user_path(@current_user) %></li>
          <li><%= link_to 'Sign Out', signout_path %><li>
          </ul>
        </nav>
      </div>
      <%= render 'layouts/flash' %>
      <% else %>
      <body class="login-page">
        <div class="wrap">
          <%= render 'layouts/flash' %>
          <% end %>
          <div class="page-content">
            <%= yield %>
          </div>
          <% unless @current_user %>
        </div>
        <% end %>
      </body>
    </html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<head>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true if !mobile_device? %>
  <%= stylesheet_link_tag 'mobile' if mobile_device? %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag '/images/favicon.ico', rel: 'apple-touch-icon', type: 'image/png' %>
  <meta name="viewport" content="initial-scale=1.0">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-transparent">
  <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
</head>
<% if @current_user %>
<html>
  <body>
    <header>
      <h1 id="banner"><%= link_to 'BOXED IN', root_path %></h1>
      <div class="button_container" id="toggle">
        <span class="top"></span>
        <span class="middle"></span>
        <span class="bottom"></span>
      </div>
    </header>
    <div class="overlay" id="overlay">
      <nav class="overlay-menu">
        <ul>
          <li><%= link_to 'Games', games_path %></li>
          <li><%= link_to 'Scores', scores_path %></li>
          <li><%= link_to 'My Account', user_path(@current_user) %></li>
          <li><%= link_to 'Sign Out', signout_path %><li>
          </ul>
        </nav>
      </div>
      <%= render 'layouts/flash' %>
      <% else %>
      <body class="login-page">
        <div class="wrap">
          <%= render 'layouts/flash' %>
          <% end %>
          <div class="page-content">
            <%= yield %>
          </div>
          <% unless @current_user %>
        </div>
        <% end %>
      </body>
    </html>